SET STATISTICS IO ON;
SET STATISTICS TIME ON;
 
PRINT 'REPLICATE';

SELECT
 TOP (8000) ROW_NUMBER() OVER(ORDER BY (SELECT 1)) AS inRowNum
FROM STRING_SPLIT(REPLICATE(CHAR(32),8000),CHAR(32));
 
 
PRINT 'SPACE';

SELECT
 TOP (8000) ROW_NUMBER() OVER(ORDER BY (SELECT 1)) AS inRowNum
FROM STRING_SPLIT(SPACE(8000),CHAR(32));

PRINT 'CTE';
 
WITH
L0   AS(SELECT 1 AS c UNION ALL SELECT 1),
L1   AS(SELECT 1 AS c FROM L0 AS A CROSS JOIN L0 AS B),
L2   AS(SELECT 1 AS c FROM L1 AS A CROSS JOIN L1 AS B),
L3   AS(SELECT 1 AS c FROM L2 AS A CROSS JOIN L2 AS B),
L4   AS(SELECT 1 AS c FROM L3 AS A CROSS JOIN L3 AS B),
L5   AS(SELECT 1 AS c FROM L4 AS A CROSS JOIN L4 AS B),
Nums AS(SELECT ROW_NUMBER() OVER(ORDER BY (SELECT NULL)) AS n FROM L5)
SELECT TOP (8000) n FROM Nums ORDER BY n;